### PR TITLE
format text

### PR DESCRIPTION
**Pull request by ZhengLin-Li**
format text according to [Chinese copywriting guidelines for better written communication／中文文案排版指北](https://github.com/sparanoid/chinese-copywriting-guidelines)

I made this PR according to the following rules: 
- [Place one space before/after English words](https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.en.md#place-one-space-beforeafter-english-words)
- [Add extra spaces before/after links](https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.en.md#add-extra-spaces-beforeafter-links)

### CODE REVIEW

**Comment by ZhengLin-Li** [comment]
I have made some sample changes related to the text format; if our community agrees on this format proposal, I am pleased to introduce [this GitHub Action](https://github.com/huacnlee/autocorrect-action) to help with our project's text format.

**Comment by Flash-321** [comment]
@ZhengLin-Li 感谢细节处的细心指正！

**Comment by Flash-321** [comment]
> I have made some sample changes related to the text format; if our community agrees on this format proposal, I am pleased to introduce [this GitHub Action](https://github.com/huacnlee/autocorrect-action) to help with our project's text format.

@ZhengLin-Li Cool, pls open a PR for this action! Thanks for your contribution. You may add a script to change the markdown docs before compile, and the final html will also be modified.

**Comment by ZhengLin-Li** [comment]
@Flash-321 I have tested the GitHub Action mentioned above, and found that it is not intended to correct our text format error automatically, but to detect if there are problems related to text format and report the problem. If there is a problem related to text format, that GitHub Action will return an error, which is not what we want. Details can be found here: https://github.com/ZhengLin-Li/csmsapp.github.io/actions/runs/4029274673/jobs/6927007189

So, I think we may manually format our text, from time to time, with the help of https://marketplace.visualstudio.com/items?itemName=huacnlee.autocorrect

I will create another PR, in which text is format using VSCode extension above.

**Comment by Flash-321** [comment]
> @Flash-321 I have tested the GitHub Action mentioned above, and found that it is not intended to correct our text format error automatically, but to detect if there are problems related to text format and report the problem. If there is a problem related to text format, that GitHub Action will return an error, which is not what we want. Details can be found here: https://github.com/ZhengLin-Li/csmsapp.github.io/actions/runs/4029274673/jobs/6927007189
> 
> So, I think we may manually format our text, from time to time, with the help of https://marketplace.visualstudio.com/items?itemName=huacnlee.autocorrect
> 
> I will create another PR, in which text is format using VSCode extension above.

@ZhengLin-Li Great, thanks for your contribution! I think you may use a file filter to only format those markdown files.

**Pull request merged**
